name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          template: terminal
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          config_timezone: Europe/Bucharest
          config_display: large
          config_animations: yes
          config_order: header, isocalendar, languages, lines, followup, topics, repositories
          base: header, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_analysis_timeout: 15
          plugin_lines: yes
          plugin_followup: yes
          plugin_topics: yes
          plugin_topics_limit: 12
